# Week 2 Project

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import torch
import torch.nn as nn

ModuleNotFoundError: No module named 'torch'

In [22]:
df = pd.read_csv('../adult.csv', na_values=['?'])
df.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,NaN,77053,HS-grad,9,Widowed,NaN,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,NaN,186061,Some-college,10,Widowed,NaN,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

In [4]:
df.shape

(32561, 15)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  str
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  str
 4   education.num   32561 non-null  int64
 5   marital.status  32561 non-null  str
 6   occupation      32561 non-null  str
 7   relationship    32561 non-null  str
 8   race            32561 non-null  str
 9   sex             32561 non-null  str
 10  capital.gain    32561 non-null  int64
 11  capital.loss    32561 non-null  int64
 12  hours.per.week  32561 non-null  int64
 13  native.country  32561 non-null  str
 14  income          32561 non-null  str
dtypes: int64(6), str(9)
memory usage: 3.7 MB

In [23]:
null_counts = df.isna().sum()
print("Missing values per column:")
print(null_counts[null_counts > 0])
print("Total missing cells:", int(null_counts.sum()))

duplicate_mask = df.duplicated(keep=False)
print("Extra duplicate rows:", int(df.duplicated().sum()))
print("Rows involved in duplicates:", int(duplicate_mask.sum()))
df.loc[duplicate_mask]

Missing values per column:
workclass         1836
occupation        1843
native.country     583
dtype: int64
Total missing cells: 4262
Extra duplicate rows: 24
Rows involved in duplicates: 47

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
6227,90,Private,52386,Some-college,10,Never-married,Other-service,Not-in-family,Asian-Pac-Islander,Male,0,0,35,United-States,<=50K
7615,19,Private,251579,Some-college,10,Never-married,Other-service,Own-child,White,Male,0,0,14,United-States,<=50K
7978,25,Private,308144,Bachelors,13,Never-married,Craft-repair,Not-in-family,White,Male,0,0,40,Mexico,<=50K
8356,21,Private,250051,Some-college,10,Never-married,Prof-specialty,Own-child,White,Female,0,0,10,United-States,<=50K
8453,25,Private,308144,Bachelors,13,Never-married,Craft-repair,Not-in-family,White,Male,0,0,40,Mexico,<=50K
8500,38,Private,207202,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,48,United-States,>50K
8645,90,Private,52386,Some-college,10,Never-married,Other-service,Not-in-family,Asian-Pac-Islander,Male,0,0,35,United-States,<=50K
9067,27,Private,255582,HS-grad,9,Never-married,Machine-op-inspct,Not-in-family,White,Female,0,0,40,United-States,<=50K
9269,20,Private,107658,Some-college,10,Never-married,Tech-support,Not-in-family,White,Female,0,0,10,United-States,<=50K
9305,25,Private,195994,1st-4th,2,Never-married,Priv-house-serv,Not-in-family,White,Female,0,0,40,Guatemala,<=50K
10307,19,Private,138153,Some-college,10,Never-married,Adm-clerical,Own-child,White,Female,0,0,10,United-States,<=50K
10357,49,Self-emp-not-inc,43479,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
11121,49,Private,31267,7th-8th,4,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
11261,21,Private,243368,Preschool,1,Never-married,Farming-fishing,Not-in-family,White,Male,0,0,50,Mexico,<=50K
11777,28,Private,274679,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,50,United-States,<=50K
12202,21,Private,250051,Some-college,10,Never-married,Prof-specialty,Own-child,White,Female,0,0,10,United-States,<=50K
13260,42,Private,204235,Some-college,10,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,>50K
14346,20,Private,107658,Some-college,10,Never-married,Tech-support,Not-in-family,White,Female,0,0,10,United-States,<=50K
14634,46,Private,133616,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
15603,25,Private,195994,1st-4th,2,Never-married,Priv-house-serv,Not-in-family,White,Female,0,0,40,Guatemala,<=50K
17344,21,Private,243368,Preschool,1,Never-married,Farming-fishing,Not-in-family,White,Male,0,0,50,Mexico,<=50K
17456,19,Private,146679,Some-college,10,Never-married,Exec-managerial,Own-child,Black,Male,0,0,30,United-States,<=50K
18417,46,Private,173243,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
18906,35,Private,379959,HS-grad,9,Divorced,Other-service,Not-in-family,White,Female,0,0,40,United-States,<=50K
19014,30,Private,144593,HS-grad,9,Never-married,Other-service,Not-in-family,Black,Male,0,0,40,NaN,<=50K
19067,46,Private,173243,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
19622,19,Private,97261,HS-grad,9,Never-married,Farming-fishing,Not-in-family,White,Male,0,0,40,United-States,<=50K
19832,44,Private,367749,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,45,Mexico,<=50K
20388,30,Private,144593,HS-grad,9,Never-married,Other-service,Not-in-family,Black,Male,0,0,40,NaN,<=50K
20507,19,Private,97261,HS-grad,9,Never-married,Farming-fishing,Not-in-family,White,Male,0,0,40,United-States,<=50K
22595,23,Private,240137,5th-6th,3,Never-married,Handlers-cleaners,Not-in-family,White,Male,0,0,55,Mexico,<=50K
22783,19,Private,138153,Some-college,10,Never-married,Adm-clerical,Own-child,White,Female,0,0,10,United-States,<=50K
22934,19,Private,146679,Some-college,10,Never-married,Exec-managerial,Own-child,Black,Male,0,0,30,United-States,<=50K
23276,49,Private,31267,7th-8th,4,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
23660,25,Private,195994,1st-4th,2,Never-married,Priv-house-serv,Not-in-family,White,Female,0,0,40,Guatemala,<=50K
23720,44,Private,367749,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,45,Mexico,<=50K
23827,49,Self-emp-not-inc,43479,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
26531,39,Private,30916,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
26738,23,Private,240137,5th-6th,3,Never-married,Handlers-cleaners,Not-in-family,White,Male,0,0,55,Mexico,<=50K
27133,28,Private,274679,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,50,United-States,<=50K
28796,27,Private,255582,HS-grad,9,Never-married,Machine-op-inspct,Not-in-family,White,Female,0,0,40,United-States,<=50K
29051,42,Private,204235,Some-college,10,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,>50K
29334,39,Private,30916,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
29604,38,Private,207202,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,48,United-States,>50K
31060,46,Private,133616,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32065,19,Private,251579,Some-college,10,Never-married,Other-service,Own-child,White,Male,0,0,14,United-States,<=50K
32419,35,Private,379959,HS-grad,9,Divorced,Other-service,Not-in-family,White,Female,0,0,40,United-States,<=50K

# handing missing values

In [10]:
df = df.replace("?", pd.NA)
df.isna().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education.num        0
marital.status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital.gain         0
capital.loss         0
hours.per.week       0
native.country     583
income               0
dtype: int64

In [12]:
for column in ["workclass", "occupation", "native.country"]:
    df[column] = df[column].fillna(df[column].mode()[0])

In [13]:
df = df.replace("?", pd.NA)
df.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64

In [14]:
duplicate_rows = df[df.duplicated(keep=False)]

print("Extra duplicate rows:", int(df.duplicated().sum()))
duplicate_rows

Extra duplicate rows: 24

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
6227,90,Private,52386,Some-college,10,Never-married,Other-service,Not-in-family,Asian-Pac-Islander,Male,0,0,35,United-States,<=50K
7615,19,Private,251579,Some-college,10,Never-married,Other-service,Own-child,White,Male,0,0,14,United-States,<=50K
7978,25,Private,308144,Bachelors,13,Never-married,Craft-repair,Not-in-family,White,Male,0,0,40,Mexico,<=50K
8356,21,Private,250051,Some-college,10,Never-married,Prof-specialty,Own-child,White,Female,0,0,10,United-States,<=50K
8453,25,Private,308144,Bachelors,13,Never-married,Craft-repair,Not-in-family,White,Male,0,0,40,Mexico,<=50K
8500,38,Private,207202,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,48,United-States,>50K
8645,90,Private,52386,Some-college,10,Never-married,Other-service,Not-in-family,Asian-Pac-Islander,Male,0,0,35,United-States,<=50K
9067,27,Private,255582,HS-grad,9,Never-married,Machine-op-inspct,Not-in-family,White,Female,0,0,40,United-States,<=50K
9269,20,Private,107658,Some-college,10,Never-married,Tech-support,Not-in-family,White,Female,0,0,10,United-States,<=50K
9305,25,Private,195994,1st-4th,2,Never-married,Priv-house-serv,Not-in-family,White,Female,0,0,40,Guatemala,<=50K
10307,19,Private,138153,Some-college,10,Never-married,Adm-clerical,Own-child,White,Female,0,0,10,United-States,<=50K
10357,49,Self-emp-not-inc,43479,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
11121,49,Private,31267,7th-8th,4,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
11261,21,Private,243368,Preschool,1,Never-married,Farming-fishing,Not-in-family,White,Male,0,0,50,Mexico,<=50K
11777,28,Private,274679,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,50,United-States,<=50K
12202,21,Private,250051,Some-college,10,Never-married,Prof-specialty,Own-child,White,Female,0,0,10,United-States,<=50K
13260,42,Private,204235,Some-college,10,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,>50K
14346,20,Private,107658,Some-college,10,Never-married,Tech-support,Not-in-family,White,Female,0,0,10,United-States,<=50K
14634,46,Private,133616,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
15603,25,Private,195994,1st-4th,2,Never-married,Priv-house-serv,Not-in-family,White,Female,0,0,40,Guatemala,<=50K
17344,21,Private,243368,Preschool,1,Never-married,Farming-fishing,Not-in-family,White,Male,0,0,50,Mexico,<=50K
17456,19,Private,146679,Some-college,10,Never-married,Exec-managerial,Own-child,Black,Male,0,0,30,United-States,<=50K
18417,46,Private,173243,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
18906,35,Private,379959,HS-grad,9,Divorced,Other-service,Not-in-family,White,Female,0,0,40,United-States,<=50K
19014,30,Private,144593,HS-grad,9,Never-married,Other-service,Not-in-family,Black,Male,0,0,40,United-States,<=50K
19067,46,Private,173243,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
19622,19,Private,97261,HS-grad,9,Never-married,Farming-fishing,Not-in-family,White,Male,0,0,40,United-States,<=50K
19832,44,Private,367749,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,45,Mexico,<=50K
20388,30,Private,144593,HS-grad,9,Never-married,Other-service,Not-in-family,Black,Male,0,0,40,United-States,<=50K
20507,19,Private,97261,HS-grad,9,Never-married,Farming-fishing,Not-in-family,White,Male,0,0,40,United-States,<=50K
22595,23,Private,240137,5th-6th,3,Never-married,Handlers-cleaners,Not-in-family,White,Male,0,0,55,Mexico,<=50K
22783,19,Private,138153,Some-college,10,Never-married,Adm-clerical,Own-child,White,Female,0,0,10,United-States,<=50K
22934,19,Private,146679,Some-college,10,Never-married,Exec-managerial,Own-child,Black,Male,0,0,30,United-States,<=50K
23276,49,Private,31267,7th-8th,4,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
23660,25,Private,195994,1st-4th,2,Never-married,Priv-house-serv,Not-in-family,White,Female,0,0,40,Guatemala,<=50K
23720,44,Private,367749,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,45,Mexico,<=50K
23827,49,Self-emp-not-inc,43479,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
26531,39,Private,30916,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
26738,23,Private,240137,5th-6th,3,Never-married,Handlers-cleaners,Not-in-family,White,Male,0,0,55,Mexico,<=50K
27133,28,Private,274679,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,50,United-States,<=50K
28796,27,Private,255582,HS-grad,9,Never-married,Machine-op-inspct,Not-in-family,White,Female,0,0,40,United-States,<=50K
29051,42,Private,204235,Some-college,10,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,>50K
29334,39,Private,30916,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
29604,38,Private,207202,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,48,United-States,>50K
31060,46,Private,133616,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32065,19,Private,251579,Some-college,10,Never-married,Other-service,Own-child,White,Male,0,0,14,United-States,<=50K
32419,35,Private,379959,HS-grad,9,Divorced,Other-service,Not-in-family,White,Female,0,0,40,United-States,<=50K

In [15]:
duplicate_counts = df.value_counts().reset_index(name='count')

In [16]:
duplicates = duplicate_counts[duplicate_counts['count'] > 1]

In [19]:
exact_duplicates = df[df.duplicated(keep=False)]
print(exact_duplicates)

       age         workclass  fnlwgt     education  education.num  \
6227    90           Private   52386  Some-college             10
7615    19           Private  251579  Some-college             10
7978    25           Private  308144     Bachelors             13
8356    21           Private  250051  Some-college             10
8453    25           Private  308144     Bachelors             13
8500    38           Private  207202       HS-grad              9
8645    90           Private   52386  Some-college             10
9067    27           Private  255582       HS-grad              9
9269    20           Private  107658  Some-college             10
9305    25           Private  195994       1st-4th              2
10307   19           Private  138153  Some-college             10
10357   49  Self-emp-not-inc   43479  Some-college             10
11121   49           Private   31267       7th-8th              4
11261   21           Private  243368     Preschool              1
11777   28           Private  274679       Masters             14
12202   21           Private  250051  Some-college             10
13260   42           Private  204235  Some-college             10
14346   20           Private  107658  Some-college             10
14634   46           Private  133616  Some-college             10
15603   25           Private  195994       1st-4th              2
17344   21           Private  243368     Preschool              1
17456   19           Private  146679  Some-college             10
18417   46           Private  173243       HS-grad              9
18906   35           Private  379959       HS-grad              9
19014   30           Private  144593       HS-grad              9
19067   46           Private  173243       HS-grad              9
19622   19           Private   97261       HS-grad              9
19832   44           Private  367749     Bachelors             13
20388   30           Private  144593       HS-grad              9
20507   19           Private   97261       HS-grad              9
22595   23           Private  240137       5th-6th              3
22783   19           Private  138153  Some-college             10
22934   19           Private  146679  Some-college             10
23276   49           Private   31267       7th-8th              4
23660   25           Private  195994       1st-4th              2
23720   44           Private  367749     Bachelors             13
23827   49  Self-emp-not-inc   43479  Some-college             10
26531   39           Private   30916       HS-grad              9
26738   23           Private  240137       5th-6th              3
27133   28           Private  274679       Masters             14
28796   27           Private  255582       HS-grad              9
29051   42           Private  204235  Some-college             10
29334   39           Private   30916       HS-grad              9
29604   38           Private  207202       HS-grad              9
31060   46           Private  133616  Some-college             10
32065   19           Private  251579  Some-college             10
32419   35           Private  379959       HS-grad              9

           marital.status         occupation   relationship  \
6227        Never-married      Other-service  Not-in-family
7615        Never-married      Other-service      Own-child
7978        Never-married       Craft-repair  Not-in-family
8356        Never-married     Prof-specialty      Own-child
8453        Never-married       Craft-repair  Not-in-family
8500   Married-civ-spouse  Machine-op-inspct        Husband
8645        Never-married      Other-service  Not-in-family
9067        Never-married  Machine-op-inspct  Not-in-family
9269        Never-married       Tech-support  Not-in-family
9305        Never-married    Priv-house-serv  Not-in-family
10307       Never-married       Adm-clerical      Own-child
10357  Married-civ-spouse       Craft-repair        Husband
11121  Married-civ-spouse       Craft-repair        Husband
11261       Never-married    Farming-fishing  Not-in-family
11777       Never-married     Prof-specialty  Not-in-family
12202       Never-married     Prof-specialty      Own-child
13260  Married-civ-spouse     Prof-specialty        Husband
14346       Never-married       Tech-support  Not-in-family
14634            Divorced       Adm-clerical      Unmarried
15603       Never-married    Priv-house-serv  Not-in-family
17344       Never-married    Farming-fishing  Not-in-family
17456       Never-married    Exec-managerial      Own-child
18417  Married-civ-spouse       Craft-repair        Husband
18906            Divorced      Other-service  Not-in-family
19014       Never-married      Other-service  Not-in-family
19067  Married-civ-spouse       Craft-repair        Husband
19622       Never-married    Farming-fishing  Not-in-family
19832       Never-married     Prof-specialty  Not-in-family
20388       Never-married      Other-service  Not-in-family
20507       Never-married    Farming-fishing  Not-in-family
22595       Never-married  Handlers-cleaners  Not-in-family
22783       Never-married       Adm-clerical      Own-child
22934       Never-married    Exec-managerial      Own-child
23276  Married-civ-spouse       Craft-repair        Husband
23660       Never-married    Priv-house-serv  Not-in-family
23720       Never-married     Prof-specialty  Not-in-family
23827  Married-civ-spouse       Craft-repair        Husband
26531  Married-civ-spouse       Craft-repair        Husband
26738       Never-married  Handlers-cleaners  Not-in-family
27133       Never-married     Prof-specialty  Not-in-family
28796       Never-married  Machine-op-inspct  Not-in-family
29051  Married-civ-spouse     Prof-specialty        Husband
29334  Married-civ-spouse       Craft-repair        Husband
29604  Married-civ-spouse  Machine-op-inspct        Husband
31060            Divorced       Adm-clerical      Unmarried
32065       Never-married      Other-service      Own-child
32419            Divorced      Other-service  Not-in-family

                     race     sex  capital.gain  capital.loss  hours.per.week  \
6227   Asian-Pac-Islander    Male             0             0              35
7615                White    Male             0             0              14
7978                White    Male             0             0              40
8356                White  Female             0             0              10
8453                White    Male             0             0              40
8500                White    Male             0             0              48
8645   Asian-Pac-Islander    Male             0             0              35
9067                White  Female             0             0              40
9269                White  Female             0             0              10
9305                White  Female             0             0              40
10307               White  Female             0             0              10
10357               White    Male             0             0              40
11121               White    Male             0             0              40
11261               White    Male             0             0              50
11777               White    Male             0             0              50
12202               White  Female             0             0              10
13260               White    Male             0             0              40
14346               White  Female             0             0              10
14634               White  Female             0             0              40
15603               White  Female             0             0              40
17344               White    Male             0             0              50
17456               Black    Male             0             0              30
18417               White    Male             0             0              40
18906               White  Female             0             0              40
19014               Black    Male             0             0              40
19067               White    Male             0             0              40
19622               White    Male             0             0              40
19832               White  Female             0             0              45
20388               Black    Male             0             0              40
20507               White    Male             0             0              40
22595               White    Male             0             0              55
22783               White  Female             0             0              10
22934               Black    Male             0             0              30
23276               White    Male             0             0              40
23660               White  Female             0             0              40
23720               White  Female             0             0              45
23827               White    Male             0             0              40
26531               White    Male             0             0              40
26738               White    Male             0             0              55
27133               White    Male             0             0              50
28796               White  Female             0             0              40
29051               White    Male             0             0              40
29334               White    Male             0             0              40
29604               White    Male             0             0              48
31060               White  Female             0             0              40
32065               White    Male             0             0              14
32419               White  Female             0             0              40

      native.country income
6227   United-States  <=50K
7615   United-States  <=50K
7978          Mexico  <=50K
8356   United-States  <=50K
8453          Mexico  <=50K
8500   United-States   >50K
8645   United-States  <=50K
9067   United-States  <=50K
9269   United-States  <=50K
9305       Guatemala  <=50K
10307  United-States  <=50K
10357  United-States  <=50K
11121  United-States  <=50K
11261         Mexico  <=50K
11777  United-States  <=50K
12202  United-States  <=50K
13260  United-States   >50K
14346  United-States  <=50K
14634  United-States  <=50K
15603      Guatemala  <=50K
17344         Mexico  <=50K
17456  United-States  <=50K
18417  United-States  <=50K
18906  United-States  <=50K
19014  United-States  <=50K
19067  United-States  <=50K
19622  United-States  <=50K
19832         Mexico  <=50K
20388  United-States  <=50K
20507  United-States  <=50K
22595         Mexico  <=50K
22783  United-States  <=50K
22934  United-States  <=50K
23276  United-States  <=50K
23660      Guatemala  <=50K
23720         Mexico  <=50K
23827  United-States  <=50K
26531  United-States  <=50K
26738         Mexico  <=50K
27133  United-States  <=50K
28796  United-States  <=50K
29051  United-States   >50K
29334  United-States  <=50K
29604  United-States   >50K
31060  United-States  <=50K
32065  United-States  <=50K
32419  United-States  <=50K